---
language: generic
dist: trusty
group: edge
sudo: required
sudo: true
install:
- "./bin/packer-build-install"
script:
- export PACKER_TEMPLATES_BRANCH="master"
- "./bin/packer-build-script ci-garnet"
env:
  matrix:
  - BUILDER=googlecompute
